### ISSUE TITLE
view-fits: invalid argument

### ISSUE THREAD

**Issue by raff** [astrogo/fitsio#16]
With go 1.6.2 on Windows and tip of x/exp/shiny the call at https://github.com/astrogo/fitsio/blob/master/cmd/view-fits/main.go#L93 returns "invalid argument".

If I change it with, for example, "b, err := s.NewBuffer(image.Point{500,500})" everything works.

**Comment by sbinet** [comment]
thanks for the report and the fix.

**Comment by sbinet** [comment]
actually, let me know if 2438fc6 really fixed it for you :)
