### ISSUE TITLE
fitsio: add examples for various image types

### ISSUE THREAD

**Issue by sbinet** [astrogo/fitsio#29]
we should add examples for reading/writing various image types (different Bitpixels, rows x cols, ...)

**Comment by brandondube** [comment]
Yes, please!

**Comment by sbinet** [comment]
what do you think about https://github.com/astrogo/fitsio/pull/48 ?

**Comment by sbinet** [comment]
see:
- https://godoc.org/github.com/astrogo/fitsio#pkg-examples

(feel free to reopen or file a new issue if it's not completely satisfying)
(thanks for maybe using `astrogo/fitsio` :P)
