### ISSUE TITLE
Reusing the I/O buffer when decoding a header unit would be beneficial

### ISSUE THREAD

**Issue by airnandez** [astrogo/fitsio#31]
The current implementation of `readBlock` allocates a new memory buffer every time a new block of 2880 bytes is to be read (see [here](https://github.com/astrogo/fitsio/blob/2daa7b8da9959c632942ea7122c5380cff36fd10/utils.go#L29)). This generates additional unnecessary work to the garbage collector when decoding thousands of files in a single execution of a program using `astrogo/fitsio`.

This situation could be improved by associating a buffer of the appropriate size to a [`streamDecoder`](https://github.com/astrogo/fitsio/blob/2daa7b8da9959c632942ea7122c5380cff36fd10/decode.go#L30) and reuse that buffer for reading each block of the same FITS file.

Alternatively, a single buffer could be allocated by the [`DecodeHDU()` method](https://github.com/astrogo/fitsio/blob/2daa7b8da9959c632942ea7122c5380cff36fd10/decode.go#L34) and that buffer could be reused to perform all the necessary read operations while decoding the entire HDU.

**Comment by sbinet** [comment]
thanks for the report.
I went with the alternative :)

**Comment by airnandez** [comment]
Excellent. Thanks !
