### ISSUE TITLE
Converting FITS to TIFF blows out

### ISSUE THREAD

**Issue by rickbassham** [astrogo/fitsio#35]
I'm trying to convert a FITS file to TIFF, but the pixel values seem way too high. I'm assuming there is something wrong with my FITS file or I'm doing something incorrectly. Any insight would be helpful.

Code:
https://gist.github.com/anonymous/269f11f5471ef013dd17bf793be094d5

FIT and TIFF:
https://drive.google.com/drive/folders/1pkY-UdsNRlQ4toMc02m2SzWUQuttS2bJ?usp=sharing

**Comment by sbinet** [comment]
I'll investigate tomorrow.
Thanks for the report :)

Do you know what AstroPy sites with this file? (So we'd know whether the FITS for is to blame or my tiff implementation. Probably the latter.)

**Comment by sbinet** [comment]
(apologies for the bad auto-complete. Corrected)

**Comment by rickbassham** [comment]
AstroPy converts it correctly.

https://gist.github.com/rickbassham/b02e7c4f095e173c220da2b216bd476c

**Comment by rickbassham** [comment]
If I scale down the pixel values (just subtract 32768 from the value) it looks correct, so probably an issue with uint16 vs int16.

**Comment by rickbassham** [comment]
Looks like fitsio isn't reading the BZERO/BSCALE header values

**Comment by sbinet** [comment]
could you try out the `issue-35` branch?
I fixed it explicitly for `ImageHDU.Image()`. I may need to think about a better place to put the rescaling...

**Comment by rickbassham** [comment]
I'll take a look when I get home from work this afternoon, but a quick look over the commit looks like it will work.

**Comment by rickbassham** [comment]
Works beautifully!
