### ISSUE TITLE
Decode: check that the number of bytes read matches the number of bytes requested

### ISSUE THREAD

**Issue by airnandez** [astrogo/fitsio#36]
When decoding a FITS file, an `io.Reader` can return both the requested number of bytes AND  an `error` (for instance EOF).

[Here]( https://github.com/astrogo/fitsio/blob/36404d4fcf9efe96f64c13675b3b192a6a442986/decode.go#L330) we should first check that the requested number of bytes were returned (here `pad`), in which case `err` can be either ignored or, best, checked against `EOF`.

**Comment by sbinet** [comment]
right.
I think it actually would be better to use `io.ReadFull`.
(care to send a PR?)

**Comment by sbinet** [comment]
(I am on holidays till 1st of March)

**Comment by airnandez** [comment]
Yes, using `io.ReadFull` would be better. I will try something on my side and send a PR.

**Comment by sbinet** [comment]
Thanks!

**Comment by airnandez** [comment]
[Pull request](https://github.com/astrogo/fitsio/pull/37) submitted.

**Comment by sbinet** [comment]
fixed with  a1d964b.
